### ISSUE TITLE
listAndWrap on ResourceBase

### ISSUE THREAD

**Issue by beschoenen** [MapCreatorEU/m4n-api#66] opened 2017-08-10 13:00 UTC
```js
api.users.select(1).mapstyles.listAndWrap()
```

**Comment by Mechazawa** [comment] 2017-08-10 14:30
`.mapstyles` should proxy to a `ResourceProxy`.

**Comment by Mechazawa** [comment] 2017-08-10 14:32
Duplicate of #65

**Closed by Mechazawa** 2017-08-10 14:32 UTC
Labels: enhancement, feature
